version: "3.3"
services:
  mysqlservice:
    image: mysql:latest
    ports:
      - 3306:3306
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Global@145#
      MYSQL_DATABASE: AuthenticationDB
      MYSQL_USERNAME: root
      #      MYSQL_PASSWORD: Global@145#
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  mongodbservice:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - 27017:27017

  configserver:
    container_name: config-server-container
    build: config-server/
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    ports:
      - 8888:8888

  eurekaserver:
    container_name: eureka-server-container
    build: eureka-server/
    ports:
      - 8761:8761

  api-gateway:
    container_name: api-gateway-container
    build: api-gateway/
    environment:
      - eureka.client.service-url.defaultZone=http://eurekaserver:8761/eureka
      - paymentservicesvc=paymentservice
      - authenticationservicesvc=authenticationservice
      - emailservicesvc=emailservice
      - appointmentservicesvc=appointmentservice
      - userservicesvc=userservice
      - productwebappsvc=product-webapp
    ports:
      - 8080:8080

  authenticationservice:
    container_name: authentication-service-container
    build: authentication-service/
    environment:
      - spring.datasource.url=jdbc:mysql://mysqlservice:3306/AuthenticationDB
    ports:
      - 8091:8091
    depends_on:
      - eurekaserver
      - configserver
      - mysqlservice
    restart: always

  emailservice:
    container_name: email-service-container
    build: email-service/
    environment:
      - spring.rabbitmq.host=rabbitmq
    ports:
      - 8088:8088
    depends_on:
      - mysqlservice
      - eurekaserver
      - configserver
      - authenticationservice
    restart: always

  appointmentservice:
    container_name: appointment-service-container
    build: appointment-service/
    environment:
      - spring.data.mongodb.uri=mongodb://mongodbservice:27017/fitpro
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    ports:
      - 8090:8090
    depends_on:
      - mongodbservice
      - eurekaserver
      - configserver
    restart: always

  paymentservice:
    container_name: payment-service-container
    build: payment-service/
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    ports:
      - 8089:8089
    depends_on:
      - mongodbservice
      - eurekaserver
      - configserver
    restart: always

  userservice:
    container_name: user-service-container
    build: user-service/
    environment:
      - enthusiast_home_page_url=http://product-webapp:8087/#/innovators
      - expert_home_page_url=http://product-webapp:8087/#/experts
      - enthusiast_redirect_url=http://userservice:8083/api/v1/authorize/enthusiast/complete
      - expert_redirect_url=http://userservice:8083/api/v1/authorize/expert/complete
      - Domain=localhosteureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka
      - logout_redirect_url=http://product-webapp:8087/#/
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka
      - spring.data.mongodb.host=mongodbservice
    ports:
      - 8083:8083
    depends_on:
      - mongodbservice
      - eurekaserver
      - configserver
    restart: always

  product-webapp:
    build: product-webapp/
    image: product-webapp
    restart: always
    container_name: product-webapp
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eurekaserver:8761/eureka/
    ports:
      - 8087:8087
    depends_on:
      - eurekaserver
      - configserver

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
